// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buffer.proto

package main;

public final class Buffer {
  private Buffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_StudentBuffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_StudentBuffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_main_ProfessorBuffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_main_ProfessorBuffer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014buffer.proto\022\004main\"\261\001\n\rStudentBuffer\022\n" +
      "\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004cell\030\003 \001(\t\022\016" +
      "\n\006gender\030\004 \001(\t\022\021\n\tbirthdate\030\005 \001(\t\022\013\n\003age" +
      "\030\006 \001(\005\022\017\n\007regDate\030\007 \001(\t\022\017\n\007address\030\010 \001(\t" +
      "\022&\n\007profBuf\030\t \003(\0132\025.main.ProfessorBuffer" +
      "\"\215\001\n\017ProfessorBuffer\022\n\n\002id\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\021\n\tbirthdate\030\003 \001(\t\022\023\n\013phoneNumber" +
      "\030\004 \001(\t\022\017\n\007address\030\005 \001(\t\022\'\n\nstudentBuf\030\006 " +
      "\003(\0132\023.main.StudentBufferB\010\n\004mainP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_main_StudentBuffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_main_StudentBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_StudentBuffer_descriptor,
        new java.lang.String[] { "Id", "Name", "Cell", "Gender", "Birthdate", "Age", "RegDate", "Address", "ProfBuf", });
    internal_static_main_ProfessorBuffer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_main_ProfessorBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_main_ProfessorBuffer_descriptor,
        new java.lang.String[] { "Id", "Name", "Birthdate", "PhoneNumber", "Address", "StudentBuf", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
