// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buffer.proto

package main;

public interface ProfessorBufferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.ProfessorBuffer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string birthdate = 3;</code>
   * @return Whether the birthdate field is set.
   */
  boolean hasBirthdate();
  /**
   * <code>optional string birthdate = 3;</code>
   * @return The birthdate.
   */
  java.lang.String getBirthdate();
  /**
   * <code>optional string birthdate = 3;</code>
   * @return The bytes for birthdate.
   */
  com.google.protobuf.ByteString
      getBirthdateBytes();

  /**
   * <code>optional string phoneNumber = 4;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional string phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>optional string phoneNumber = 4;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  java.util.List<main.StudentBuffer> 
      getStudentBufList();
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  main.StudentBuffer getStudentBuf(int index);
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  int getStudentBufCount();
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  java.util.List<? extends main.StudentBufferOrBuilder> 
      getStudentBufOrBuilderList();
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  main.StudentBufferOrBuilder getStudentBufOrBuilder(
      int index);
}
