// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buffer.proto

package main;

/**
 * Protobuf type {@code main.ProfessorBuffer}
 */
public final class ProfessorBuffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:main.ProfessorBuffer)
    ProfessorBufferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProfessorBuffer.newBuilder() to construct.
  private ProfessorBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProfessorBuffer() {
    name_ = "";
    birthdate_ = "";
    phoneNumber_ = "";
    address_ = "";
    studentBuf_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProfessorBuffer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProfessorBuffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            birthdate_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            phoneNumber_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            address_ = bs;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              studentBuf_ = new java.util.ArrayList<main.StudentBuffer>();
              mutable_bitField0_ |= 0x00000020;
            }
            studentBuf_.add(
                input.readMessage(main.StudentBuffer.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        studentBuf_ = java.util.Collections.unmodifiableList(studentBuf_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.Buffer.internal_static_main_ProfessorBuffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.Buffer.internal_static_main_ProfessorBuffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.ProfessorBuffer.class, main.ProfessorBuffer.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object birthdate_;
  /**
   * <code>optional string birthdate = 3;</code>
   * @return Whether the birthdate field is set.
   */
  @java.lang.Override
  public boolean hasBirthdate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string birthdate = 3;</code>
   * @return The birthdate.
   */
  @java.lang.Override
  public java.lang.String getBirthdate() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        birthdate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string birthdate = 3;</code>
   * @return The bytes for birthdate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthdateBytes() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birthdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 4;
  private volatile java.lang.Object phoneNumber_;
  /**
   * <code>optional string phoneNumber = 4;</code>
   * @return Whether the phoneNumber field is set.
   */
  @java.lang.Override
  public boolean hasPhoneNumber() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  @java.lang.Override
  public java.lang.String getPhoneNumber() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        phoneNumber_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string phoneNumber = 4;</code>
   * @return The bytes for phoneNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneNumberBytes() {
    java.lang.Object ref = phoneNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phoneNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object address_;
  /**
   * <code>optional string address = 5;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string address = 5;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENTBUF_FIELD_NUMBER = 6;
  private java.util.List<main.StudentBuffer> studentBuf_;
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  @java.lang.Override
  public java.util.List<main.StudentBuffer> getStudentBufList() {
    return studentBuf_;
  }
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends main.StudentBufferOrBuilder> 
      getStudentBufOrBuilderList() {
    return studentBuf_;
  }
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  @java.lang.Override
  public int getStudentBufCount() {
    return studentBuf_.size();
  }
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  @java.lang.Override
  public main.StudentBuffer getStudentBuf(int index) {
    return studentBuf_.get(index);
  }
  /**
   * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
   */
  @java.lang.Override
  public main.StudentBufferOrBuilder getStudentBufOrBuilder(
      int index) {
    return studentBuf_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birthdate_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phoneNumber_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
    }
    for (int i = 0; i < studentBuf_.size(); i++) {
      output.writeMessage(6, studentBuf_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, birthdate_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phoneNumber_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
    }
    for (int i = 0; i < studentBuf_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, studentBuf_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof main.ProfessorBuffer)) {
      return super.equals(obj);
    }
    main.ProfessorBuffer other = (main.ProfessorBuffer) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasBirthdate() != other.hasBirthdate()) return false;
    if (hasBirthdate()) {
      if (!getBirthdate()
          .equals(other.getBirthdate())) return false;
    }
    if (hasPhoneNumber() != other.hasPhoneNumber()) return false;
    if (hasPhoneNumber()) {
      if (!getPhoneNumber()
          .equals(other.getPhoneNumber())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getStudentBufList()
        .equals(other.getStudentBufList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasBirthdate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
    }
    if (hasPhoneNumber()) {
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getStudentBufCount() > 0) {
      hash = (37 * hash) + STUDENTBUF_FIELD_NUMBER;
      hash = (53 * hash) + getStudentBufList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static main.ProfessorBuffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.ProfessorBuffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.ProfessorBuffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.ProfessorBuffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.ProfessorBuffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.ProfessorBuffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.ProfessorBuffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.ProfessorBuffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.ProfessorBuffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static main.ProfessorBuffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.ProfessorBuffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.ProfessorBuffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.ProfessorBuffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code main.ProfessorBuffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:main.ProfessorBuffer)
      main.ProfessorBufferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.Buffer.internal_static_main_ProfessorBuffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.Buffer.internal_static_main_ProfessorBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.ProfessorBuffer.class, main.ProfessorBuffer.Builder.class);
    }

    // Construct using main.ProfessorBuffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentBufFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      birthdate_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      phoneNumber_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (studentBufBuilder_ == null) {
        studentBuf_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        studentBufBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.Buffer.internal_static_main_ProfessorBuffer_descriptor;
    }

    @java.lang.Override
    public main.ProfessorBuffer getDefaultInstanceForType() {
      return main.ProfessorBuffer.getDefaultInstance();
    }

    @java.lang.Override
    public main.ProfessorBuffer build() {
      main.ProfessorBuffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public main.ProfessorBuffer buildPartial() {
      main.ProfessorBuffer result = new main.ProfessorBuffer(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.birthdate_ = birthdate_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.phoneNumber_ = phoneNumber_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.address_ = address_;
      if (studentBufBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          studentBuf_ = java.util.Collections.unmodifiableList(studentBuf_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.studentBuf_ = studentBuf_;
      } else {
        result.studentBuf_ = studentBufBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.ProfessorBuffer) {
        return mergeFrom((main.ProfessorBuffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.ProfessorBuffer other) {
      if (other == main.ProfessorBuffer.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBirthdate()) {
        bitField0_ |= 0x00000004;
        birthdate_ = other.birthdate_;
        onChanged();
      }
      if (other.hasPhoneNumber()) {
        bitField0_ |= 0x00000008;
        phoneNumber_ = other.phoneNumber_;
        onChanged();
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000010;
        address_ = other.address_;
        onChanged();
      }
      if (studentBufBuilder_ == null) {
        if (!other.studentBuf_.isEmpty()) {
          if (studentBuf_.isEmpty()) {
            studentBuf_ = other.studentBuf_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureStudentBufIsMutable();
            studentBuf_.addAll(other.studentBuf_);
          }
          onChanged();
        }
      } else {
        if (!other.studentBuf_.isEmpty()) {
          if (studentBufBuilder_.isEmpty()) {
            studentBufBuilder_.dispose();
            studentBufBuilder_ = null;
            studentBuf_ = other.studentBuf_;
            bitField0_ = (bitField0_ & ~0x00000020);
            studentBufBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentBufFieldBuilder() : null;
          } else {
            studentBufBuilder_.addAllMessages(other.studentBuf_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.ProfessorBuffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.ProfessorBuffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object birthdate_ = "";
    /**
     * <code>optional string birthdate = 3;</code>
     * @return Whether the birthdate field is set.
     */
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @return The birthdate.
     */
    public java.lang.String getBirthdate() {
      java.lang.Object ref = birthdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birthdate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @return The bytes for birthdate.
     */
    public com.google.protobuf.ByteString
        getBirthdateBytes() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @param value The birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      birthdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirthdate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      birthdate_ = getDefaultInstance().getBirthdate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 3;</code>
     * @param value The bytes for birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      birthdate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phoneNumber_ = "";
    /**
     * <code>optional string phoneNumber = 4;</code>
     * @return Whether the phoneNumber field is set.
     */
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string phoneNumber = 4;</code>
     * @return The phoneNumber.
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phoneNumber_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phoneNumber = 4;</code>
     * @return The bytes for phoneNumber.
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phoneNumber = 4;</code>
     * @param value The phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      phoneNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNumber = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNumber() {
      bitField0_ = (bitField0_ & ~0x00000008);
      phoneNumber_ = getDefaultInstance().getPhoneNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNumber = 4;</code>
     * @param value The bytes for phoneNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      phoneNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000010);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 5;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      address_ = value;
      onChanged();
      return this;
    }

    private java.util.List<main.StudentBuffer> studentBuf_ =
      java.util.Collections.emptyList();
    private void ensureStudentBufIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        studentBuf_ = new java.util.ArrayList<main.StudentBuffer>(studentBuf_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        main.StudentBuffer, main.StudentBuffer.Builder, main.StudentBufferOrBuilder> studentBufBuilder_;

    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public java.util.List<main.StudentBuffer> getStudentBufList() {
      if (studentBufBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentBuf_);
      } else {
        return studentBufBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public int getStudentBufCount() {
      if (studentBufBuilder_ == null) {
        return studentBuf_.size();
      } else {
        return studentBufBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public main.StudentBuffer getStudentBuf(int index) {
      if (studentBufBuilder_ == null) {
        return studentBuf_.get(index);
      } else {
        return studentBufBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder setStudentBuf(
        int index, main.StudentBuffer value) {
      if (studentBufBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentBufIsMutable();
        studentBuf_.set(index, value);
        onChanged();
      } else {
        studentBufBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder setStudentBuf(
        int index, main.StudentBuffer.Builder builderForValue) {
      if (studentBufBuilder_ == null) {
        ensureStudentBufIsMutable();
        studentBuf_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentBufBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder addStudentBuf(main.StudentBuffer value) {
      if (studentBufBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentBufIsMutable();
        studentBuf_.add(value);
        onChanged();
      } else {
        studentBufBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder addStudentBuf(
        int index, main.StudentBuffer value) {
      if (studentBufBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentBufIsMutable();
        studentBuf_.add(index, value);
        onChanged();
      } else {
        studentBufBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder addStudentBuf(
        main.StudentBuffer.Builder builderForValue) {
      if (studentBufBuilder_ == null) {
        ensureStudentBufIsMutable();
        studentBuf_.add(builderForValue.build());
        onChanged();
      } else {
        studentBufBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder addStudentBuf(
        int index, main.StudentBuffer.Builder builderForValue) {
      if (studentBufBuilder_ == null) {
        ensureStudentBufIsMutable();
        studentBuf_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentBufBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder addAllStudentBuf(
        java.lang.Iterable<? extends main.StudentBuffer> values) {
      if (studentBufBuilder_ == null) {
        ensureStudentBufIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentBuf_);
        onChanged();
      } else {
        studentBufBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder clearStudentBuf() {
      if (studentBufBuilder_ == null) {
        studentBuf_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        studentBufBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public Builder removeStudentBuf(int index) {
      if (studentBufBuilder_ == null) {
        ensureStudentBufIsMutable();
        studentBuf_.remove(index);
        onChanged();
      } else {
        studentBufBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public main.StudentBuffer.Builder getStudentBufBuilder(
        int index) {
      return getStudentBufFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public main.StudentBufferOrBuilder getStudentBufOrBuilder(
        int index) {
      if (studentBufBuilder_ == null) {
        return studentBuf_.get(index);  } else {
        return studentBufBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public java.util.List<? extends main.StudentBufferOrBuilder> 
         getStudentBufOrBuilderList() {
      if (studentBufBuilder_ != null) {
        return studentBufBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentBuf_);
      }
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public main.StudentBuffer.Builder addStudentBufBuilder() {
      return getStudentBufFieldBuilder().addBuilder(
          main.StudentBuffer.getDefaultInstance());
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public main.StudentBuffer.Builder addStudentBufBuilder(
        int index) {
      return getStudentBufFieldBuilder().addBuilder(
          index, main.StudentBuffer.getDefaultInstance());
    }
    /**
     * <code>repeated .main.StudentBuffer studentBuf = 6;</code>
     */
    public java.util.List<main.StudentBuffer.Builder> 
         getStudentBufBuilderList() {
      return getStudentBufFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        main.StudentBuffer, main.StudentBuffer.Builder, main.StudentBufferOrBuilder> 
        getStudentBufFieldBuilder() {
      if (studentBufBuilder_ == null) {
        studentBufBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            main.StudentBuffer, main.StudentBuffer.Builder, main.StudentBufferOrBuilder>(
                studentBuf_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        studentBuf_ = null;
      }
      return studentBufBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:main.ProfessorBuffer)
  }

  // @@protoc_insertion_point(class_scope:main.ProfessorBuffer)
  private static final main.ProfessorBuffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.ProfessorBuffer();
  }

  public static main.ProfessorBuffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ProfessorBuffer>
      PARSER = new com.google.protobuf.AbstractParser<ProfessorBuffer>() {
    @java.lang.Override
    public ProfessorBuffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProfessorBuffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProfessorBuffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProfessorBuffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public main.ProfessorBuffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

