// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buffer.proto

package main;

/**
 * Protobuf type {@code main.StudentBuffer}
 */
public final class StudentBuffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:main.StudentBuffer)
    StudentBufferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentBuffer.newBuilder() to construct.
  private StudentBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentBuffer() {
    name_ = "";
    cell_ = "";
    gender_ = "";
    birthdate_ = "";
    regDate_ = "";
    address_ = "";
    profBuf_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StudentBuffer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentBuffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            cell_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            gender_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            birthdate_ = bs;
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            age_ = input.readInt32();
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            regDate_ = bs;
            break;
          }
          case 66: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000080;
            address_ = bs;
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) != 0)) {
              profBuf_ = new java.util.ArrayList<main.ProfessorBuffer>();
              mutable_bitField0_ |= 0x00000100;
            }
            profBuf_.add(
                input.readMessage(main.ProfessorBuffer.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) != 0)) {
        profBuf_ = java.util.Collections.unmodifiableList(profBuf_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.Buffer.internal_static_main_StudentBuffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.Buffer.internal_static_main_StudentBuffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.StudentBuffer.class, main.StudentBuffer.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CELL_FIELD_NUMBER = 3;
  private volatile java.lang.Object cell_;
  /**
   * <code>optional string cell = 3;</code>
   * @return Whether the cell field is set.
   */
  @java.lang.Override
  public boolean hasCell() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string cell = 3;</code>
   * @return The cell.
   */
  @java.lang.Override
  public java.lang.String getCell() {
    java.lang.Object ref = cell_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        cell_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string cell = 3;</code>
   * @return The bytes for cell.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCellBytes() {
    java.lang.Object ref = cell_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cell_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 4;
  private volatile java.lang.Object gender_;
  /**
   * <code>optional string gender = 4;</code>
   * @return Whether the gender field is set.
   */
  @java.lang.Override
  public boolean hasGender() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string gender = 4;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gender_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string gender = 4;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 5;
  private volatile java.lang.Object birthdate_;
  /**
   * <code>optional string birthdate = 5;</code>
   * @return Whether the birthdate field is set.
   */
  @java.lang.Override
  public boolean hasBirthdate() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string birthdate = 5;</code>
   * @return The birthdate.
   */
  @java.lang.Override
  public java.lang.String getBirthdate() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        birthdate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string birthdate = 5;</code>
   * @return The bytes for birthdate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthdateBytes() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      birthdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 6;
  private int age_;
  /**
   * <code>optional int32 age = 6;</code>
   * @return Whether the age field is set.
   */
  @java.lang.Override
  public boolean hasAge() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 age = 6;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  public static final int REGDATE_FIELD_NUMBER = 7;
  private volatile java.lang.Object regDate_;
  /**
   * <code>optional string regDate = 7;</code>
   * @return Whether the regDate field is set.
   */
  @java.lang.Override
  public boolean hasRegDate() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string regDate = 7;</code>
   * @return The regDate.
   */
  @java.lang.Override
  public java.lang.String getRegDate() {
    java.lang.Object ref = regDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        regDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string regDate = 7;</code>
   * @return The bytes for regDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegDateBytes() {
    java.lang.Object ref = regDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      regDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 8;
  private volatile java.lang.Object address_;
  /**
   * <code>optional string address = 8;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional string address = 8;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        address_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string address = 8;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFBUF_FIELD_NUMBER = 9;
  private java.util.List<main.ProfessorBuffer> profBuf_;
  /**
   * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
   */
  @java.lang.Override
  public java.util.List<main.ProfessorBuffer> getProfBufList() {
    return profBuf_;
  }
  /**
   * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends main.ProfessorBufferOrBuilder> 
      getProfBufOrBuilderList() {
    return profBuf_;
  }
  /**
   * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
   */
  @java.lang.Override
  public int getProfBufCount() {
    return profBuf_.size();
  }
  /**
   * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
   */
  @java.lang.Override
  public main.ProfessorBuffer getProfBuf(int index) {
    return profBuf_.get(index);
  }
  /**
   * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
   */
  @java.lang.Override
  public main.ProfessorBufferOrBuilder getProfBufOrBuilder(
      int index) {
    return profBuf_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cell_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, birthdate_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, age_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, regDate_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, address_);
    }
    for (int i = 0; i < profBuf_.size(); i++) {
      output.writeMessage(9, profBuf_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cell_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, birthdate_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, age_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, regDate_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, address_);
    }
    for (int i = 0; i < profBuf_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, profBuf_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof main.StudentBuffer)) {
      return super.equals(obj);
    }
    main.StudentBuffer other = (main.StudentBuffer) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasCell() != other.hasCell()) return false;
    if (hasCell()) {
      if (!getCell()
          .equals(other.getCell())) return false;
    }
    if (hasGender() != other.hasGender()) return false;
    if (hasGender()) {
      if (!getGender()
          .equals(other.getGender())) return false;
    }
    if (hasBirthdate() != other.hasBirthdate()) return false;
    if (hasBirthdate()) {
      if (!getBirthdate()
          .equals(other.getBirthdate())) return false;
    }
    if (hasAge() != other.hasAge()) return false;
    if (hasAge()) {
      if (getAge()
          != other.getAge()) return false;
    }
    if (hasRegDate() != other.hasRegDate()) return false;
    if (hasRegDate()) {
      if (!getRegDate()
          .equals(other.getRegDate())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getProfBufList()
        .equals(other.getProfBufList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasCell()) {
      hash = (37 * hash) + CELL_FIELD_NUMBER;
      hash = (53 * hash) + getCell().hashCode();
    }
    if (hasGender()) {
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
    }
    if (hasBirthdate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
    }
    if (hasAge()) {
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
    }
    if (hasRegDate()) {
      hash = (37 * hash) + REGDATE_FIELD_NUMBER;
      hash = (53 * hash) + getRegDate().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getProfBufCount() > 0) {
      hash = (37 * hash) + PROFBUF_FIELD_NUMBER;
      hash = (53 * hash) + getProfBufList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static main.StudentBuffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.StudentBuffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.StudentBuffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.StudentBuffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.StudentBuffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.StudentBuffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.StudentBuffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.StudentBuffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.StudentBuffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static main.StudentBuffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.StudentBuffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.StudentBuffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.StudentBuffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code main.StudentBuffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:main.StudentBuffer)
      main.StudentBufferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.Buffer.internal_static_main_StudentBuffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.Buffer.internal_static_main_StudentBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.StudentBuffer.class, main.StudentBuffer.Builder.class);
    }

    // Construct using main.StudentBuffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProfBufFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      cell_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      gender_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      birthdate_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      age_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      regDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      address_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      if (profBufBuilder_ == null) {
        profBuf_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        profBufBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.Buffer.internal_static_main_StudentBuffer_descriptor;
    }

    @java.lang.Override
    public main.StudentBuffer getDefaultInstanceForType() {
      return main.StudentBuffer.getDefaultInstance();
    }

    @java.lang.Override
    public main.StudentBuffer build() {
      main.StudentBuffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public main.StudentBuffer buildPartial() {
      main.StudentBuffer result = new main.StudentBuffer(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.cell_ = cell_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.gender_ = gender_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.birthdate_ = birthdate_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.age_ = age_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.regDate_ = regDate_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        to_bitField0_ |= 0x00000080;
      }
      result.address_ = address_;
      if (profBufBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          profBuf_ = java.util.Collections.unmodifiableList(profBuf_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.profBuf_ = profBuf_;
      } else {
        result.profBuf_ = profBufBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.StudentBuffer) {
        return mergeFrom((main.StudentBuffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.StudentBuffer other) {
      if (other == main.StudentBuffer.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasCell()) {
        bitField0_ |= 0x00000004;
        cell_ = other.cell_;
        onChanged();
      }
      if (other.hasGender()) {
        bitField0_ |= 0x00000008;
        gender_ = other.gender_;
        onChanged();
      }
      if (other.hasBirthdate()) {
        bitField0_ |= 0x00000010;
        birthdate_ = other.birthdate_;
        onChanged();
      }
      if (other.hasAge()) {
        setAge(other.getAge());
      }
      if (other.hasRegDate()) {
        bitField0_ |= 0x00000040;
        regDate_ = other.regDate_;
        onChanged();
      }
      if (other.hasAddress()) {
        bitField0_ |= 0x00000080;
        address_ = other.address_;
        onChanged();
      }
      if (profBufBuilder_ == null) {
        if (!other.profBuf_.isEmpty()) {
          if (profBuf_.isEmpty()) {
            profBuf_ = other.profBuf_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureProfBufIsMutable();
            profBuf_.addAll(other.profBuf_);
          }
          onChanged();
        }
      } else {
        if (!other.profBuf_.isEmpty()) {
          if (profBufBuilder_.isEmpty()) {
            profBufBuilder_.dispose();
            profBufBuilder_ = null;
            profBuf_ = other.profBuf_;
            bitField0_ = (bitField0_ & ~0x00000100);
            profBufBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProfBufFieldBuilder() : null;
          } else {
            profBufBuilder_.addAllMessages(other.profBuf_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.StudentBuffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.StudentBuffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cell_ = "";
    /**
     * <code>optional string cell = 3;</code>
     * @return Whether the cell field is set.
     */
    public boolean hasCell() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string cell = 3;</code>
     * @return The cell.
     */
    public java.lang.String getCell() {
      java.lang.Object ref = cell_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cell_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cell = 3;</code>
     * @return The bytes for cell.
     */
    public com.google.protobuf.ByteString
        getCellBytes() {
      java.lang.Object ref = cell_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cell_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cell = 3;</code>
     * @param value The cell to set.
     * @return This builder for chaining.
     */
    public Builder setCell(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      cell_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cell = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCell() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cell_ = getDefaultInstance().getCell();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cell = 3;</code>
     * @param value The bytes for cell to set.
     * @return This builder for chaining.
     */
    public Builder setCellBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      cell_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <code>optional string gender = 4;</code>
     * @return Whether the gender field is set.
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gender_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gender = 4;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      bitField0_ = (bitField0_ & ~0x00000008);
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 4;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      gender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object birthdate_ = "";
    /**
     * <code>optional string birthdate = 5;</code>
     * @return Whether the birthdate field is set.
     */
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string birthdate = 5;</code>
     * @return The birthdate.
     */
    public java.lang.String getBirthdate() {
      java.lang.Object ref = birthdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birthdate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string birthdate = 5;</code>
     * @return The bytes for birthdate.
     */
    public com.google.protobuf.ByteString
        getBirthdateBytes() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string birthdate = 5;</code>
     * @param value The birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      birthdate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBirthdate() {
      bitField0_ = (bitField0_ & ~0x00000010);
      birthdate_ = getDefaultInstance().getBirthdate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 5;</code>
     * @param value The bytes for birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      birthdate_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>optional int32 age = 6;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 age = 6;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>optional int32 age = 6;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      bitField0_ |= 0x00000020;
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 age = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000020);
      age_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object regDate_ = "";
    /**
     * <code>optional string regDate = 7;</code>
     * @return Whether the regDate field is set.
     */
    public boolean hasRegDate() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string regDate = 7;</code>
     * @return The regDate.
     */
    public java.lang.String getRegDate() {
      java.lang.Object ref = regDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          regDate_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string regDate = 7;</code>
     * @return The bytes for regDate.
     */
    public com.google.protobuf.ByteString
        getRegDateBytes() {
      java.lang.Object ref = regDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string regDate = 7;</code>
     * @param value The regDate to set.
     * @return This builder for chaining.
     */
    public Builder setRegDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      regDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string regDate = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegDate() {
      bitField0_ = (bitField0_ & ~0x00000040);
      regDate_ = getDefaultInstance().getRegDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string regDate = 7;</code>
     * @param value The bytes for regDate to set.
     * @return This builder for chaining.
     */
    public Builder setRegDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      regDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>optional string address = 8;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string address = 8;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string address = 8;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string address = 8;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000080);
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string address = 8;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      address_ = value;
      onChanged();
      return this;
    }

    private java.util.List<main.ProfessorBuffer> profBuf_ =
      java.util.Collections.emptyList();
    private void ensureProfBufIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        profBuf_ = new java.util.ArrayList<main.ProfessorBuffer>(profBuf_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        main.ProfessorBuffer, main.ProfessorBuffer.Builder, main.ProfessorBufferOrBuilder> profBufBuilder_;

    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public java.util.List<main.ProfessorBuffer> getProfBufList() {
      if (profBufBuilder_ == null) {
        return java.util.Collections.unmodifiableList(profBuf_);
      } else {
        return profBufBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public int getProfBufCount() {
      if (profBufBuilder_ == null) {
        return profBuf_.size();
      } else {
        return profBufBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public main.ProfessorBuffer getProfBuf(int index) {
      if (profBufBuilder_ == null) {
        return profBuf_.get(index);
      } else {
        return profBufBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder setProfBuf(
        int index, main.ProfessorBuffer value) {
      if (profBufBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfBufIsMutable();
        profBuf_.set(index, value);
        onChanged();
      } else {
        profBufBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder setProfBuf(
        int index, main.ProfessorBuffer.Builder builderForValue) {
      if (profBufBuilder_ == null) {
        ensureProfBufIsMutable();
        profBuf_.set(index, builderForValue.build());
        onChanged();
      } else {
        profBufBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder addProfBuf(main.ProfessorBuffer value) {
      if (profBufBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfBufIsMutable();
        profBuf_.add(value);
        onChanged();
      } else {
        profBufBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder addProfBuf(
        int index, main.ProfessorBuffer value) {
      if (profBufBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfBufIsMutable();
        profBuf_.add(index, value);
        onChanged();
      } else {
        profBufBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder addProfBuf(
        main.ProfessorBuffer.Builder builderForValue) {
      if (profBufBuilder_ == null) {
        ensureProfBufIsMutable();
        profBuf_.add(builderForValue.build());
        onChanged();
      } else {
        profBufBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder addProfBuf(
        int index, main.ProfessorBuffer.Builder builderForValue) {
      if (profBufBuilder_ == null) {
        ensureProfBufIsMutable();
        profBuf_.add(index, builderForValue.build());
        onChanged();
      } else {
        profBufBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder addAllProfBuf(
        java.lang.Iterable<? extends main.ProfessorBuffer> values) {
      if (profBufBuilder_ == null) {
        ensureProfBufIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, profBuf_);
        onChanged();
      } else {
        profBufBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder clearProfBuf() {
      if (profBufBuilder_ == null) {
        profBuf_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        profBufBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public Builder removeProfBuf(int index) {
      if (profBufBuilder_ == null) {
        ensureProfBufIsMutable();
        profBuf_.remove(index);
        onChanged();
      } else {
        profBufBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public main.ProfessorBuffer.Builder getProfBufBuilder(
        int index) {
      return getProfBufFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public main.ProfessorBufferOrBuilder getProfBufOrBuilder(
        int index) {
      if (profBufBuilder_ == null) {
        return profBuf_.get(index);  } else {
        return profBufBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public java.util.List<? extends main.ProfessorBufferOrBuilder> 
         getProfBufOrBuilderList() {
      if (profBufBuilder_ != null) {
        return profBufBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(profBuf_);
      }
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public main.ProfessorBuffer.Builder addProfBufBuilder() {
      return getProfBufFieldBuilder().addBuilder(
          main.ProfessorBuffer.getDefaultInstance());
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public main.ProfessorBuffer.Builder addProfBufBuilder(
        int index) {
      return getProfBufFieldBuilder().addBuilder(
          index, main.ProfessorBuffer.getDefaultInstance());
    }
    /**
     * <code>repeated .main.ProfessorBuffer profBuf = 9;</code>
     */
    public java.util.List<main.ProfessorBuffer.Builder> 
         getProfBufBuilderList() {
      return getProfBufFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        main.ProfessorBuffer, main.ProfessorBuffer.Builder, main.ProfessorBufferOrBuilder> 
        getProfBufFieldBuilder() {
      if (profBufBuilder_ == null) {
        profBufBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            main.ProfessorBuffer, main.ProfessorBuffer.Builder, main.ProfessorBufferOrBuilder>(
                profBuf_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        profBuf_ = null;
      }
      return profBufBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:main.StudentBuffer)
  }

  // @@protoc_insertion_point(class_scope:main.StudentBuffer)
  private static final main.StudentBuffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.StudentBuffer();
  }

  public static main.StudentBuffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<StudentBuffer>
      PARSER = new com.google.protobuf.AbstractParser<StudentBuffer>() {
    @java.lang.Override
    public StudentBuffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentBuffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentBuffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentBuffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public main.StudentBuffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

